### PR TITLE
Fix problem with websocket when the connection upgrade failed

### LINKED ISSUE #1174: Traefik is routing traffic to wrong backend.
### What version of Traefik are you using (`traefik version`)?
~~v1.1.2~~
**Edit:** also present with `v1.2.0-rc1`

### What is your environment & configuration (arguments, toml...)?
Traefik is running in a Docker container on CoreOS and pulling config from etcd and all traffic is routed through Cloudflare first (ddos protection).

etcd config: (taken from debug log `Configuration received from provider etcd:`)
```json
{
  "backends": {
    "b1": {
      "servers": {
        "10.133.102.22": {
          "url": "http://10.133.102.22",
          "weight": 0
        },
        "10.133.92.63": {
          "url": "http://10.133.92.63",
          "weight": 0
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    },
    "b2": {
      "servers": {
        "10.133.13.121": {
          "url": "http://10.133.13.121",
          "weight": 0
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    },
    "b3": {
      "servers": {
        "grafana": {
          "url": "http://10.133.59.44",
          "weight": 0
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    },
    "b4": {
      "servers": {
        "10.133.21.211": {
          "url": "http://10.133.21.211",
          "weight": 0
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    },
    "b5": {
      "servers": {
        "emq": {
          "url": "http://10.133.112.89:8090",
          "weight": 0
        }
      },
      "loadBalancer": {
        "method": "wrr"
      }
    }
  },
  "frontends": {
    "f1": {
      "entryPoints": [
        "http"
      ],
      "backend": "b1",
      "routes": {
        "r1": {
          "rule": "HostRegexp:admin.foobar.com,secure.foobar.com,{subdomain:(config|queue|status)}.barfoo.eu,barfoo.eu"
        }
      },
      "passHostHeader": true,
      "priority": 0
    },
    "f2": {
      "entryPoints": [
        "http"
      ],
      "backend": "b2",
      "routes": {
        "r1": {
          "rule": "HostRegexp:dev.foobar.com,secure.dev.foobar.com,{subdomain:(config|queue|status)}.dev.barfoo.eu,dev.barfoo.eu"
        }
      },
      "passHostHeader": true,
      "priority": 0
    },
    "f3": {
      "entryPoints": [
        "http"
      ],
      "backend": "b3",
      "routes": {
        "r1": {
          "rule": "Host:grafana.foobar.com"
        }
      },
      "passHostHeader": true,
      "priority": 0
    },
    "f4": {
      "entryPoints": [
        "http"
      ],
      "backend": "b4",
      "routes": {
        "r1": {
          "rule": "Host:api.foobar.com"
        }
      },
      "passHostHeader": true,
      "priority": 0
    },
    "f5": {
      "entryPoints": [
        "http"
      ],
      "backend": "b5",
      "routes": {
        "r1": {
          "rule": "Host:ws.foobar.com,ws.barfoo.eu"
        }
      },
      "passHostHeader": true,
      "priority": 0
    }
  }
}
```

### What did you do?
Point backend b5 to another server (the old server did also host the load balancer but on a different port).

### What did you expect to see?
That traffic from only frontend f5 get forwarded to b5.

### What did you see instead?
That some traffic from f1 (primary traffic to `admin.foobar.com`) get forwarded to b5

Another thing I observed, none of the request which is forwarded to the wrong server is in the access log, also I haven't be able to reproduce the issue with `curl`, but I did look at the headers with help from tcpdump and everything looked as it should (I have posted log in the Slack [channel](https://traefik.slack.com/archives/support/p1487507299003070)).

Edit: Another thing, b5 is used for websocket, if that has anything to say. Maybe that somehow screw something up? Also feel free to ping me on the slack channel.

/cc @containous

### PR DESCRIPTION
**Pull request by juliens**
fix https://github.com/containous/traefik/issues/1174

### CODE REVIEW

**Comment by juliens** [comment]
I have made some tests with traefik in order to be sure there was no memory leak with this add.

I have launch traefik in debug (last release version and the version with this oxy version). With one backend/frontend (emilevauge/whoami)

I have used expvarmon in order to track memory changes (https://github.com/divan/expvarmon)

Then I have tried with 500 websocket client that just send a random data, then wait for response. All this connections were renew randomly.
capture du 2017-06-20 10-17-44


As we can see in the screenshot, the behavior is the same.

Finally I launch 
```bash
wrk -H "Host: backend1.com" -H "Upgrade: websocket" -H "Connection: Upgrade" http://127.0.0.1:8080/echo -d 1000
```

With this test, we can see the behavior when the Switching protocol failed. As we can see, there is more allocation with the new version because before the change, traefik didn't even know that some requests were done. But we see that there is no memory leak.
capture du 2017-06-20 14-24-04

**Review by emilevauge — APPROVED** [review]
Thanks a lot @Juliens :)
LGTM

**Comment by emilevauge** [comment]
@klausenbusk your review on this PR [makes sense](https://github.com/containous/traefik/issues/1174#issuecomment-283473267) :)

**Review by ldez — APPROVED** [review]
LGTM

**Pull request merged**
