### PR TITLE
Setting the cookie path to '/' 

### PR DESCRIPTION
**Pull request by marcopaga**
Related to containous/traefik#1744

### CODE REVIEW

**Comment by timoreimann** [comment]
@ldez is a design review in order?

**Comment by ldez** [comment]
Yes.

We don't have labels on this repo. I will fix that.

**Comment by emilevauge** [comment]
Design LGTM :)

**Review by emilevauge — APPROVED** [review]
Thanks @marcopaga 
LGTM

**Review by ldez — APPROVED** [review]
LGTM

**Review by timoreimann — APPROVED** [review]

**Pull request merged**
