### PR TITLE
Fix goroutine leak in websocket

### PR DESCRIPTION
**Pull request by juliens**
Fix a leak in websocket

To explain:

We have two goroutines, one for the connection with the backend, and one for the connection with the client.

If an error occurs on one of the goroutines, we close both connection. By buffering the err channel, we can ignore the error on the goroutine which occurs because we close the connection intentionally.

### CODE REVIEW

**Review by emilevauge — APPROVED** [review]
LGTM

**Review by ldez — APPROVED** [review]
LGTM

**Review by m3co-code — APPROVED** [review]
LGTM, I had the same fix in mind. I can verify tomorrow morning whether it fixes the problem in our setup, maybe a good idea before pushing to a bug fix release. WDYT? Is it planned that we do a 1.5.2 for this one?

**Comment by emilevauge** [comment]
@marco-jantke good idea, we will push 1.5.2 next week so that's all good :)

**Pull request merged**
